const fs = require('fs');

const DICT = {
  // Science Optics & Physics
  "कांच": "कांच / Glass",
  "पानी": "पानी / Water",
  "हीरा": "हीरा / Diamond",
  "उत्तल लेंस": "उत्तल लेंस / Convex Lens",
  "बाइफोकल लेंस": "बाइफोकल लेंस / Bifocal Lens",
  "बेलनाकार लेंस": "बेलनाकार लेंस / Cylindrical Lens",
  "अवतल लेंस": "अवतल लेंस / Concave Lens",
  "समतल लेंस": "समतल लेंस / Plane Lens",
  "सिलिंड्रिकल": "सिलिंड्रिकल लेंस / Cylindrical Lens",
  "उत्तल दर्पण": "उत्तल दर्पण / Convex Mirror",
  "समतल दर्पण": "समतल दर्पण / Plane Mirror",
  "परवलयिक दर्पण": "परवलयिक दर्पण / Parabolic Mirror",
  "अवतल दर्पण": "अवतल दर्पण / Concave Mirror",
  "उभयोत्तल": "उभयोत्तल लेंस / Biconvex Lens",
  "मीटर": "मीटर / Metre",
  "ल्यूमेन": "ल्यूमेन / Lumen",
  "वाट": "वाट / Watt",
  "पीला": "पीला / Yellow",
  "हरा": "हरा / Green",
  "प्रकाश का अपवर्तन": "प्रकाश का अपवर्तन / Refraction of Light",
  "प्रकाश का परावर्तन": "प्रकाश का परावर्तन / Reflection of Light",
  "पूर्ण आंतरिक परावर्तन": "पूर्ण आंतरिक परावर्तन / Total Internal Reflection",
  "ओम": "ओम / Ohm",
  "महो": "महो / Mho (Siemens)",
  "3.6 × 10⁶ जूल": "3.6 × 10⁶ जूल / 3.6 × 10⁶ Joules (1 kWh)",
  "3.6 × 10⁵ जूल": "3.6 × 10⁵ जूल / 3.6 × 10⁵ Joules",
  "10³ जूल": "10³ जूल / 10³ Joules",
  "746 जूल": "746 जूल / 746 Joules",
  "फ्लेमिंग के दाएं हाथ का नियम": "फ्लेमिंग के दाएं हाथ का नियम / Fleming's Right-Hand Rule",
  "मैक्सवेल का कॉर्कस्क्रू नियम": "मैक्सवेल का कॉर्कस्क्रू नियम / Maxwell's Corkscrew Rule",
  "फैराडे का नियम": "फैराडे का नियम / Faraday's Law",
  "काला": "काला / Black",
  "ऑक्सीजन": "ऑक्सीजन / Oxygen (O₂)",
  "हाइड्रोजन": "हाइड्रोजन / Hydrogen (H₂)",
  "क्लोरीन": "क्लोरीन / Chlorine (Cl₂)",
  "बैंगनी": "बैंगनी / Violet",
  "ब्रोमीन": "ब्रोमीन / Bromine (Br)",
  "सोडियम": "सोडियम / Sodium (Na)",
  "सीसा": "सीसा / Lead (Pb)",
  "ग्रेफाइट": "ग्रेफाइट / Graphite",
  "प्लैटिनम": "प्लैटिनम / Platinum",
  "टंगस्टन": "टंगस्टन / Tungsten (W)",
  "पेप्सिन": "पेप्सिन / Pepsin",
  "ट्रिप्सिन": "ट्रिप्सिन / Trypsin",
  "पित्त रस": "पित्त रस / Bile Juice",
  "सल्फ्यूरिक अम्ल": "सल्फ्यूरिक अम्ल / Sulphuric Acid (H₂SO₄)",
  "नाइट्रिक अम्ल": "नाइट्रिक अम्ल / Nitric Acid (HNO₃)",
  "एसिटिक अम्ल": "एसिटिक अम्ल / Acetic Acid (CH₃COOH)",
  "पैरेंकाइमा": "पैरेंकाइमा / Parenchyma",
  "कोलेंकाइमा": "कोलेंकाइमा / Collenchyma",
  "न्यूरॉन": "न्यूरॉन (तंत्रिका कोशिका) / Neuron",
  "कोशिका": "कोशिका / Cell",
  "कूपिका": "कूपिका (एल्वियोली) / Alveoli",
  "ऑक्सिन": "ऑक्सिन / Auxin",
  "जिबरेलिन": "जिबरेलिन / Gibberellin",
  "एब्सिसिक अम्ल": "एब्सिसिक अम्ल / Abscisic Acid (ABA)",
  "यकृत": "यकृत / Liver",
  "थायरॉयड": "थायरॉयड ग्रंथि / Thyroid Gland",
  "पीयूष ग्रंथि": "पीयूष ग्रंथि (मास्टर ग्रंथि) / Pituitary Gland",
  "चना": "चना / Gram",
  "सरसों": "सरसों / Mustard",
  "गेहूं": "गेहूं / Wheat",
  "ऑटोसोम": "ऑटोसोम (अलिंग गुणसूत्र) / Autosomes",
  "10% (लिंडेमान का 10% नियम)": "10% (लिंडेमान का नियम) / 10% (Lindeman's Law)",
  "अवरक्त किरणें": "अवरक्त किरणें / Infrared Rays",
  "गामा किरणें": "गामा किरणें / Gamma Rays",
  "एक्स-रे": "एक्स-रे / X-Rays",
  "1.33 (जल)": "1.33 (जल / Water)",
  "1.50 (कांच)": "1.50 (कांच / Glass)",
  "प्रकाश सघन से विरल माध्यम में जाए और आपतन कोण > क्रांतिक कोण": "प्रकाश सघन से विरल माध्यम में जाए (i > ic) / Light goes from denser to rarer with i > ic",
  "प्रकाश विरल से सघन में जाए": "प्रकाश विरल से सघन में जाए / Light goes from rarer to denser",
  "आपतन कोण = 90°": "आपतन कोण = 90° / Angle of incidence = 90°",
  "कोई भी माध्यम": "कोई भी माध्यम / Any medium",
  "25 मीटर": "25 मीटर / 25 metres",
  "2.5 सेमी": "2.5 सेमी / 2.5 cm",
  "अनंत": "अनंत / Infinity (∞)",
  "अपवर्तन, विक्षेपण तथा आंतरिक परावर्तन": "अपवर्तन, विक्षेपण तथा आंतरिक परावर्तन / Refraction, Dispersion and Internal Reflection",
  "केवल परावर्तन": "केवल परावर्तन / Only Reflection",
  "केवल प्रकीर्णन": "केवल प्रकीर्णन / Only Scattering",
  "व्यतिकरण": "व्यतिकरण / Interference",
  "तांबा": "तांबा / Copper (Cu)",
  "एल्युमिनियम": "एल्युमिनियम / Aluminium (Al)",
  "शून्य": "शून्य / Zero (0)",
  "सिरों पर अधिकतम": "सिरों पर अधिकतम / Maximum at ends",
  "असमान": "असमान / Unequal",
  "हैंस क्रिश्चियन ओरस्टेड": "हैंस क्रिश्चियन ओरस्टेड / Hans Christian Oersted",
  "जेम्स क्लर्क मैक्सवेल": "जेम्स क्लर्क मैक्सवेल / James Clerk Maxwell",
  "आइजैक न्यूटन": "आइजैक न्यूटन / Isaac Newton",
  "ऊष्माशोषी अभिक्रिया": "ऊष्माशोषी अभिक्रिया / Endothermic Reaction",
  "संयोजन": "संयोजन अभिक्रिया / Combination Reaction",
  "अपघटन": "अपघटन अभिक्रिया / Decomposition Reaction",
  "अपचयन": "अपचयन अभिक्रिया / Reduction Reaction",
  "केवल भौतिक परिवर्तन": "केवल भौतिक परिवर्तन / Only Physical Change",
  "अवक्षेपण": "अवक्षेपण अभिक्रिया / Precipitation Reaction",
  "पीला ही रहता है": "पीला ही रहता है / Remains Yellow",
  "नीला": "नीला / Blue",
  "सिट्रिक अम्ल": "सिट्रिक अम्ल / Citric Acid",
  "टार्टरिक अम्ल": "टार्टरिक अम्ल / Tartaric Acid",
  "एसिटिक अम्ल (5-8% एथेनॉइक अम्ल)": "एसिटिक अम्ल (5-8% एथेनॉइक) / Acetic Acid (Vinegar)",
  "ऑक्जेलिक अम्ल": "ऑक्जेलिक अम्ल / Oxalic Acid",
  "लैक्टिक अम्ल": "लैक्टिक अम्ल / Lactic Acid",
  "प्लास्टर ऑफ पेरिस": "प्लास्टर ऑफ पेरिस / Plaster of Paris (CaSO₄·½H₂O)",
  "जिप्सम": "जिप्सम / Gypsum (CaSO₄·2H₂O)",
  "बुझा चूना": "बुझा चूना / Slaked Lime [Ca(OH)₂]",
  "एनोडीकरण": "एनोडीकरण / Anodising",
  "विद्युतलेपन": "विद्युतलेपन / Electroplating",
  "मिश्रधातु निर्माण": "मिश्रधातु निर्माण / Alloying",
  "चांदी": "चांदी / Silver (Ag)",
  "लोहा और कार्बन": "लोहा और कार्बन / Iron and Carbon (Steel)",
  "4 कोष्ठ (2 आलिंद और 2 निलय)": "4 कोष्ठ (2 आलिंद, 2 निलय) / 4 Chambers (2 Atria, 2 Ventricles)",
  "3 कोष्ठ": "3 कोष्ठ / 3 Chambers",
  "2 कोष्ठ": "2 कोष्ठ / 2 Chambers",
  "6 कोष्ठ": "6 कोष्ठ / 6 Chambers",
  "क्लोरोफिल": "क्लोरोफिल / Chlorophyll",
  "प्लेटलेट्स": "प्लेटलेट्स (रक्त बिम्बाणु) / Platelets",
  "प्लाज्मा": "प्लाज्मा / Plasma",
  "हीमोग्लोबिन": "हीमोग्लोबिन / Haemoglobin",
  "यूरिक अम्ल": "यूरिक अम्ल / Uric Acid",
  "नेफ्रॉन": "नेफ्रॉन (वृक्काणु) / Nephron",
  "रीढ़ की हड्डी": "रीढ़ की हड्डी (मेरुरज्जु) / Spinal Cord",
  "प्रमस्तिष्क": "प्रमस्तिष्क (सेरेब्रम) / Cerebrum",
  "मेडुला ऑबलोंगेटा": "मेडुला ऑबलोंगेटा / Medulla Oblongata",
  "पोंस": "पोंस / Pons",
  "थायरॉयड ग्रंथि": "थायरॉयड ग्रंथि / Thyroid Gland",
  "अग्न्याशय": "अग्न्याशय (आइलेट्स ऑफ लैंगरहैंड्स) / Pancreas",
  "लोहा": "लोहा / Iron (Fe)",
  "कैल्शियम": "कैल्शियम / Calcium (Ca)",
  "फास्फोरस": "फास्फोरस / Phosphorus (P)",
  "द्विखंडन": "द्विखंडन / Binary Fission",
  "बीजाणु समासंघ": "बीजाणु समासंघ / Spore Formation",
  "पुनर्जनन": "पुनर्जनन / Regeneration",
  "मुकुलन": "मुकुलन / Budding",
  "खंडन": "खंडन / Fragmentation",
  "कायिक प्रवर्धन": "कायिक प्रवर्धन / Vegetative Propagation",
  "गर्भाशय": "गर्भाशय / Uterus",
  "अंडाशय": "अंडाशय / Ovary",
  "योनि": "योनि / Vagina",
  "3 : 1 (3 लंबा : 1 बौना)": "3 : 1 (3 लंबा : 1 बौना) / 3 : 1 (Monohybrid Phenotype)",
  "1 : 2 : 1 (जीनप्ररूपी)": "1 : 2 : 1 (जीनप्ररूपी) / 1 : 2 : 1 (Genotypic Ratio)",
  "जैव अपघटन": "जैव अपघटन / Biodegradation",
  "प्रकाश संश्लेषण": "प्रकाश संश्लेषण / Photosynthesis",
  "कार्बन डाइऑक्साइड": "कार्बन डाइऑक्साइड / Carbon Dioxide (CO₂)",
  "मीथेन": "मीथेन (बायोगैस) / Methane (CH₄)",
  "सल्फर डाइऑक्साइड": "सल्फर डाइऑक्साइड / Sulphur Dioxide (SO₂)",
  "सोडियम क्लोराइड": "सोडियम क्लोराइड / Sodium Chloride (NaCl)",
  "नीला अवक्षेप": "नीला अवक्षेप / Blue Precipitate",
  "पीला अवक्षेप": "पीला अवक्षेप / Yellow Precipitate",
  "हाइड्रोजन गैस": "हाइड्रोजन गैस / Hydrogen Gas (H₂)",
  "नाइट्रोजन": "नाइट्रोजन / Nitrogen (N₂)",
  "अम्लीय": "अम्लीय / Acidic",
  "उदासीन": "उदासीन / Neutral",
  "उभयधर्मी": "उभयधर्मी ऑक्साइड / Amphoteric Oxide",
  "एस्टरीकरण": "एस्टरीकरण / Esterification",
  "हाइड्रोजनीकरण": "हाइड्रोजनीकरण / Hydrogenation",
  "किण्वन": "किण्वन / Fermentation",
  "श्वेत रक्त कणिकाएं": "श्वेत रक्त कणिकाएं (WBC) / White Blood Cells",
  "क्लोरोफिल (पर्णहरित)": "क्लोरोफिल (पर्णहरित) / Chlorophyll",
  "कैरोटीन": "कैरोटीन / Carotene",
  "जैंथोफिल": "जैंथोफिल / Xanthophyll",
  "क्लोरोप्लास्ट": "क्लोरोप्लास्ट (हरितलवक) / Chloroplast",
  "जाइलम": "जाइलम (दारू ऊतक) / Xylem",
  "वातरंध्र": "वातरंध्र (लेंटिसेल) / Lenticels",
  "थायरॉक्सिन": "थायरॉक्सिन हार्मोन / Thyroxine Hormone",
  "इंसुलिन": "इंसुलिन हार्मोन / Insulin Hormone",
  "एस्ट्रोजन": "एस्ट्रोजन (मादा लिंग हार्मोन) / Estrogen",
  "निषेचन": "निषेचन / Fertilisation",
  "अंकुरण": "अंकुरण / Germination",
  "23 जोड़े (कुल 46)": "23 जोड़े (कुल 46) / 23 Pairs (46 Chromosomes)",
  "22 जोड़े": "22 जोड़े / 22 Pairs",
  "24 जोड़े": "24 जोड़े / 24 Pairs",
  "ओम का नियम": "ओम का नियम / Ohm's Law (V = IR)",
  "न्यूटन का नियम": "न्यूटन का गति नियम / Newton's Law of Motion",
  "जूल का नियम": "जूल का तापन नियम / Joule's Heating Law",
  "समांतर क्रम में": "समांतर क्रम में / In Parallel Combination",
  "मिश्रित क्रम में": "मिश्रित क्रम में / In Mixed Combination",
  "किसी भी क्रम में": "किसी भी क्रम में / In Any Sequence",
  "उच्च गलनांक": "उच्च गलनांक / High Melting Point",
  "बहुत मोटा तार": "बहुत मोटा तार / Very Thick Wire",
  "अचालक": "अचालक / Insulator",
  "एशिया": "एशिया / Asia",
  "यूरोप": "यूरोप / Europe",
  "अफ्रीका": "अफ्रीका / Africa",
  
  // Social Science & History
  "13 अप्रैल 1919 (अमृतसर, पंजाब)": "13 अप्रैल 1919 (अमृतसर) / 13 April 1919 (Amritsar)",
  "10 मई 1857 (मेरठ)": "10 मई 1857 (मेरठ) / 10 May 1857 (Meerut)",
  "12 मार्च 1930 (दांडी)": "12 मार्च 1930 (दांडी) / 12 March 1930 (Dandi)",
  "8 अगस्त 1942 (मुंबई)": "8 अगस्त 1942 (मुंबई) / 8 August 1942 (Quit India)",
  "12 मार्च 1930 (साबरमती आश्रम से)": "12 मार्च 1930 (साबरमती) / 12 March 1930 (Sabarmati)",
  "6 अप्रैल 1930": "6 अप्रैल 1930 / 6 April 1930 (Dandi Salt Law)",
  "1 अगस्त 1920": "1 अगस्त 1920 / 1 August 1920 (Non-Cooperation)",
  "26 जनवरी 1930": "26 जनवरी 1930 / 26 January 1930 (Poorna Swaraj)",
  "चंपारण (बिहार) - तिनकठिया प्रणाली के विरुद्ध": "चंपारण (बिहार) - तिनकठिया / Champaran (Bihar) 1917",
  "खेड़ा (गुजरात)": "खेड़ा (गुजरात) / Kheda (Gujarat) 1918",
  "अहमदाबाद मिल मजदूर": "अहमदाबाद मिल मजदूर / Ahmedabad Mill Strike 1918",
  "बारदोली": "बारदोली सत्याग्रह / Bardoli Satyagraha 1928",
  "काउंट कावूर": "काउंट कावूर / Count Cavour",
  "गैरीबाल्डी": "ग्यूसेप गैरीबाल्डी / Giuseppe Garibaldi",
  "मेटरनिख": "ड्यूक मेटरनिख / Duke Metternich",
  "नेपोलियन": "नेपोलियन बोनापार्ट / Napoleon Bonaparte",
  "जलोढ़ मिट्टी": "जलोढ़ मिट्टी / Alluvial Soil",
  "लाल और पीली मिट्टी": "लाल और पीली मिट्टी / Red and Yellow Soil",
  "लैटेराइट मिट्टी": "लैटेराइट मिट्टी / Laterite Soil",
  "काली मिट्टी": "काली मिट्टी (रेगुर) / Black Soil (Regur)",
  "मरुस्थली मिट्टी": "मरुस्थली मिट्टी / Arid / Desert Soil",
  "पर्वतीय मिट्टी": "पर्वतीय मिट्टी / Forest / Mountain Soil",
  "महानदी (ओडिशा)": "महानदी (ओडिशा) / Mahanadi River (Hirakud Dam)",
  "सतलुज": "सतलुज नदी / Sutlej River (Bhakra Nangal)",
  "नर्मदा": "नर्मदा नदी / Narmada River (Sardar Sarovar)",
  "गंगा": "गंगा नदी / Ganga River",
  "मक्का": "मक्का / Maize",
  "कपास": "कपास / Cotton",
  "डिगबोई (असम)": "डिगबोई (असम) / Digboi (Assam - Oldest Oilfield)",
  "बॉम्बे हाई": "बॉम्बे हाई / Mumbai High (Offshore)",
  "अंकलेश्वर (गुजरात)": "अंकलेश्वर (गुजरात) / Ankleshwar (Gujarat)",
  "कलोल": "कलोल / Kalol Oilfield",
  "1947 (समानता)": "1947 (स्वतंत्रता) / 1947 (Independence)",
  "1950 (संघवाद)": "1950 (संविधान लागू) / 1950 (Constitution Enforced)",
  "1971 (धर्मनिरपेक्षता)": "1971 / Year 1971",
  "संघ सूची": "संघ सूची / Union List",
  "राज्य सूची": "राज्य सूची / State List",
  "समवर्ती सूची": "समवर्ती सूची / Concurrent List",
  "अवशिष्ट सूची": "अवशिष्ट विषय / Residuary Subjects",
  "73वां संविधान संशोधन (1992)": "73वां संविधान संशोधन (पंचायती राज) / 73rd Amendment Act 1992",
  "74वां संविधान संशोधन": "74वां संविधान संशोधन (नगरपालिका) / 74th Amendment (Municipalities)",
  "42वां संशोधन": "42वां संशोधन (लघु संविधान) / 42nd Amendment 1976",
  "44वां संशोधन": "44वां संशोधन (1978) / 44th Amendment 1978",
  "संवैधानिक उपचारों का अधिकार (अनुच्छेद 32)": "संवैधानिक उपचारों का अधिकार / Right to Constitutional Remedies (Art 32)",
  "समानता का अधिकार (अनुच्छेद 14)": "समानता का अधिकार / Right to Equality (Art 14)",
  "स्वतंत्रता का अधिकार (अनुच्छेद 19)": "स्वतंत्रता का अधिकार / Right to Freedom (Art 19)",
  "धार्मिक स्वतंत्रता का अधिकार": "धार्मिक स्वतंत्रता का अधिकार / Right to Freedom of Religion (Art 25)",
  "प्राथमिक क्षेत्रक": "प्राथमिक क्षेत्रक (कृषि) / Primary Sector (Agriculture)",
  "द्वितीयक क्षेत्रक": "द्वितीयक क्षेत्रक (विनिर्माण) / Secondary Sector (Manufacturing)",
  "तृतीयक क्षेत्रक": "तृतीयक क्षेत्रक (सेवा) / Tertiary Sector (Services)",
  "चतुर्थक क्षेत्रक": "चतुर्थक क्षेत्रक (सूचना) / Quaternary Sector",
  "मौसमी बेरोजगारी": "मौसमी बेरोजगारी / Seasonal Unemployment",
  "चक्रीय बेरोजगारी": "चक्रीय बेरोजगारी / Cyclical Unemployment",
  "प्रच्छन्न बेरोजगारी": "प्रच्छन्न (छिपी हुई) बेरोजगारी / Disguised Unemployment",
  "ऐच्छिक बेरोजगारी": "ऐच्छिक बेरोजगारी / Voluntary Unemployment",
  "वित्त मंत्रालय": "वित्त मंत्रालय (भारत सरकार) / Ministry of Finance (Govt of India)",
  "स्टेट बैंक ऑफ इंडिया": "भारतीय स्टेट बैंक / State Bank of India (SBI)",
  "नीति आयोग": "नीति आयोग / NITI Aayog",
  "15 मार्च": "15 मार्च (विश्व उपभोक्ता अधिकार दिवस) / 15 March (World Consumer Rights Day)",
  "1 मई": "1 मई (अंतर्राष्ट्रीय मजदूर दिवस) / 1 May (Labour Day)",
  "2 अक्टूबर": "2 अक्टूबर (गांधी जयंती) / 2 October (Gandhi Jayanti)",
  "बैरोमीटर": "बैरोमीटर (वायुदाबमापी) / Barometer",
  "केल्विन पैमाना": "केल्विन पैमाना / Kelvin Scale",
  "हाइड्रोमीटर": "हाइड्रोमीटर (घनत्वमापी) / Hydrometer",
  "चक्रवात": "चक्रवात / Cyclone",
  "ज्वार-भाटा": "ज्वार-भाटा / Tides",
  "अत्यधिक वर्षा": "अत्यधिक वर्षा / Excessive Rainfall",
  "काकोरी कांड": "काकोरी ट्रेन एक्शन (1925) / Kakori Train Action",
  "जलियांवाला बाग": "जलियांवाला बाग हत्याकांड / Jallianwala Bagh Massacre",
  "मेरठ छावनी": "मेरठ छावनी (1857) / Meerut Cantonment",
  "1928 (इसमें एक भी भारतीय सदस्य नहीं था)": "1928 (साइमन कमीशन - कोई भारतीय नहीं) / 1928 (Simon Commission - All White)",
  "1919 (रौलट एक्ट के विरोध में)": "1919 (रौलट सत्याग्रह) / 1919 (Rowlatt Satyagraha)",
  "लाहौर अधिवेशन (पंडित जवाहरलाल नेहरू की अध्यक्षता)": "लाहौर अधिवेशन (पूर्ण स्वराज) / Lahore Session 1929 (Pt Nehru)",
  "कराची अधिवेशन": "कराची अधिवेशन (1931) / Karachi Session 1931",
  "सूरत अधिवेशन": "सूरत अधिवेशन (1907 विभाजन) / Surat Split 1907",
  "कोलकाता अधिवेशन": "कोलकाता अधिवेशन / Kolkata Session",
  "सविनय अवज्ञा आंदोलन": "सविनय अवज्ञा आंदोलन / Civil Disobedience Movement (1930)",
  "असहयोग आंदोलन": "असहयोग आंदोलन / Non-Cooperation Movement (1920)",
  "खिलाफत आंदोलन": "खिलाफत आंदोलन / Khilafat Movement (1919)",
  "महात्मा गांधी और डॉ. भीमराव अंबेडकर": "महात्मा गांधी और डॉ. बी.आर. अंबेडकर / Mahatma Gandhi & Dr B.R. Ambedkar (Poona Pact)",
  "गांधी और लॉर्ड इरविन": "गांधी और लॉर्ड इरविन / Gandhi & Lord Irwin (1931)",
  "नेहरू और जिन्ना": "नेहरू और जिन्ना / Nehru & Jinnah",
  "सुभाष चंद्र बोस और गांधी": "सुभाष चंद्र बोस और गांधी / Subhas Chandra Bose & Gandhi",
  "फ्रांस": "फ्रांस / France",
  "जर्मनी": "जर्मनी / Germany",
  "अमेरिका": "संयुक्त राज्य अमेरिका / United States of America",
  "मार्को पोलो": "मार्को पोलो / Marco Polo",
  "मार्टिन लूथर": "मार्टिन लूथर (धर्म सुधारक) / Martin Luther",
  "इरास्मस": "डेसिडेरियस इरास्मस / Desiderius Erasmus",
  "सुंदरलाल बहुगुणा, चंडी प्रसाद भट्ट एवं गौरा देवी": "सुंदरलाल बहुगुणा व गौरा देवी (चिपको) / S.L. Bahuguna & Gaura Devi (Chipko)",
  "मेधा पाटकर": "मेधा पाटकर (नर्मदा बचाओ) / Medha Patkar (Narmada)",
  "बाबा आमटे": "बाबा आमटे / Baba Amte",
  "सलीम अली": "डॉ. सलीम अली (बर्डमैन) / Dr Salim Ali",
  "1973 (जिम कॉर्बेट नेशनल पार्क से)": "1973 (प्रोजेक्ट टाइगर - कॉर्बेट) / 1973 (Project Tiger - Corbett)",
  "नर्मदा नदी (गुजरात)": "नर्मदा नदी (सरदार सरोवर बांध) / Narmada River (Sardar Sarovar Dam)",
  "ताप्ती": "ताप्ती नदी / Tapi River",
  "कृष्णा": "कृष्णा नदी (नागार्जुन सागर) / Krishna River",
  "कावेरी": "कावेरी नदी (मेट्टूर बांध) / Kaveri River",
  "उत्तर-दक्षिण गलियारा": "उत्तर-दक्षिण गलियारा (श्रीनगर से कन्याकुमारी) / North-South Corridor",
  "भारतमाला परियोजना": "भारतमाला परियोजना / Bharatmala Pariyojana",
  "पूर्व-पश्चिम गलियारा": "पूर्व-पश्चिम गलियारा (सिलचर से पोरबंदर) / East-West Corridor",
  "डॉ. वर्गीज कुरियन (श्वेत क्रांति)": "डॉ. वर्गीज कुरियन (श्वेत क्रांति/अमूल) / Dr Verghese Kurien (White Revolution)",
  "नॉर्मन बोरलॉग (वैश्विक जनक)": "डॉ. नॉर्मन बोरलॉग (हरित क्रांति) / Dr Norman Borlaug (Green Revolution)",
  "डॉ. विक्रम साराभाई": "डॉ. विक्रम साराभाई (अंतरिक्ष जनक) / Dr Vikram Sarabhai",
  "जॉर्ज वाशिंगटन": "जॉर्ज वाशिंगटन / George Washington",
  "अरस्तू": "अरस्तू / Aristotle",
  "रूसो": "जीन-जैक्स रूसो / Jean-Jacques Rousseau",
  "डॉ. राजेंद्र प्रसाद": "डॉ. राजेंद्र प्रसाद (स्थायी अध्यक्ष) / Dr Rajendra Prasad (Permanent President)",
  "डॉ. सच्चिदानंद सिन्हा (अस्थायी)": "डॉ. सच्चिदानंद सिन्हा (अस्थायी अध्यक्ष) / Dr Sachchidananda Sinha (Interim)",
  "डॉ. बी. आर. अंबेडकर (प्रारूप समिति)": "डॉ. बी. आर. आंबेडकर (प्रारूप समिति अध्यक्ष) / Dr B.R. Ambedkar (Drafting Chairman)",
  "पं. जवाहरलाल नेहरू": "पं. जवाहरलाल नेहरू (उद्देश्य प्रस्ताव) / Pt Jawaharlal Nehru",
  "अनुच्छेद 14": "अनुच्छेद 14 (विधि के समक्ष समानता) / Article 14 (Equality before Law)",
  "अनुच्छेद 18": "अनुच्छेद 18 (उपाधियों का अंत) / Article 18 (Abolition of Titles)",
  "अनुच्छेद 19": "अनुच्छेद 19 (वाक् एवं अभिव्यक्ति स्वतंत्रता) / Article 19 (Freedom of Speech)",
  "समानता का अधिकार": "समानता का अधिकार / Right to Equality (Articles 14-18)",
  "भाषण की स्वतंत्रता": "भाषण व अभिव्यक्ति की स्वतंत्रता / Freedom of Speech & Expression",
  "शोषण के विरुद्ध अधिकार": "शोषण के विरुद्ध अधिकार / Right against Exploitation (Articles 23-24)",
  "1995 (जिनेवा, स्विट्जरलैंड)": "1995 (WTO जिनेवा) / 1995 (World Trade Organization, Geneva)",
  "1945 (न्यूयॉर्क)": "1945 (UNO न्यूयॉर्क) / 1945 (United Nations Org, New York)",
  "1991 (वाशिंगटन)": "1991 (वाशिंगटन) / 1991 (Washington)",
  "2000 (पेरिस)": "2000 (पेरिस) / 2000 (Paris)",
  "गंडक": "गंडक नदी / Gandak River",
  "सोन नदी": "सोन नदी / Son River",
  "बेगम हजरत महल": "बेगम हजरत महल (लखनऊ 1857) / Begum Hazrat Mahal (Lucknow)",
  "रानी लक्ष्मीबाई (झांसी)": "रानी लक्ष्मीबाई (झांसी 1857) / Rani Lakshmibai (Jhansi)",
  "कुंवर सिंह (बिहार)": "वीर कुंवर सिंह (बिहार 1857) / Veer Kunwar Singh (Bihar)",
  "नाना साहेब (कानपुर)": "नाना साहेब (कानपुर 1857) / Nana Saheb (Kanpur)",
  "ब्यास": "ब्यास नदी / Beas River",
  "रावी": "रावी नदी / Ravi River",
  "चिनाब": "चिनाब नदी / Chenab River",
  "अनुच्छेद 324": "अनुच्छेद 324 (निर्वाचन आयोग) / Article 324 (Election Commission)",
  "अनुच्छेद 356": "अनुच्छेद 356 (राष्ट्रपति शासन) / Article 356 (President's Rule)",
  "अनुच्छेद 280": "अनुच्छेद 280 (वित्त आयोग) / Article 280 (Finance Commission)",
  "अनुच्छेद 368": "अनुच्छेद 368 (संविधान संशोधन) / Article 368 (Constitutional Amendment)",
  "अमर्त्य सेन": "प्रो. अमर्त्य सेन (नोबेल पुरस्कार) / Prof Amartya Sen",
  "पी.सी. महालनोबिस": "पी. सी. महालनोबिस (सांख्यिकीविद) / P.C. Mahalanobis",
  "वी.के.आर.वी. राव": "डॉ. वी.के.आर.वी. राव / Dr V.K.R.V. Rao",
  "एशियाई शेर (गिर, गुजरात)": "एशियाई शेर (गिर राष्ट्रीय उद्यान) / Asiatic Lion (Gir, Gujarat)",
  "रॉयल बंगाल टाइगर": "रॉयल बंगाल टाइगर (सुंदरबन) / Royal Bengal Tiger (Sundarbans)",
  "सफेद हाथी": "सफेद हाथी / White Elephant (Thailand)",

  // Mathematics terms
  "अशांत अनावर्ती": "अशांत अनावर्ती (अपरिमेय) / Non-terminating Non-repeating (Irrational)",
  "अनिर्धारित": "अनिर्धारित / Undetermined",
  "कोई हल नहीं": "कोई हल नहीं / No Solution (Parallel Lines)",
  "केवल एक हल": "केवल एक अद्वितीय हल / Exactly One Unique Solution",
  "दो हल": "दो हल / Two Distinct Solutions",
  "वास्तविक एवं समान": "वास्तविक एवं समान मूल (D = 0) / Real and Equal Roots",
  "वास्तविक एवं भिन्न": "वास्तविक एवं भिन्न मूल (D > 0) / Real and Distinct Roots",
  "अपरिमेय": "अपरिमेय / Irrational",
  "2√2 मात्रक": "2√2 मात्रक / 2√2 units",
  "√8 मात्रक": "√8 मात्रक / √8 units",
  "4 मात्रक": "4 मात्रक / 4 units",
  "2 मात्रक": "2 मात्रक / 2 units",
  "10 मात्रक": "10 मात्रक / 10 units",
  "14 मात्रक": "14 मात्रक / 14 units",
  "8 मात्रक": "8 मात्रक / 8 units",
  "6 मात्रक": "6 मात्रक / 6 units",
  "समकोण (90°)": "समकोण (90°) / Right Angle (90°)",
  "π मात्रक": "π मात्रक / π units",
  "7 मात्रक": "7 मात्रक / 7 units",
  "8 गुना": "8 गुना / 8 times",
  "4 गुना": "4 गुना / 4 times",
  "2 गुना": "2 गुना / 2 times",
  "16 गुना": "16 गुना / 16 times",
  "बहुलक = 3 माध्यक - 2 माध्य": "बहुलक = 3 माध्यक - 2 माध्य / Mode = 3 Median - 2 Mean",
  "बहुलक = 2 माध्यक - 3 माध्य": "बहुलक = 2 माध्यक - 3 माध्य / Mode = 2 Median - 3 Mean",
  "3 बहुलक = माध्यक - 2 माध्य": "3 बहुलक = माध्यक - 2 माध्य",
  "माध्यक = 3 बहुलक - 2 माध्य": "माध्यक = 3 बहुलक - 2 माध्य",
  "7.2 दिन": "7.2 दिन / 7.2 Days",
  "8 दिन": "8 दिन / 8 Days",
  "6 दिन": "6 दिन / 6 Days",
  "7.5 दिन": "7.5 दिन / 7.5 Days",
  "2 (एकमात्र सम अभाज्य संख्या)": "2 (एकमात्र सम अभाज्य) / 2 (Only Even Prime)",
  "अनंत हल": "अनंत अनेक हल / Infinitely Many Solutions",
  "प्रथम": "प्रथम चतुर्थांश / First Quadrant (+,+)",
  "द्वितीय": "द्वितीय चतुर्थांश / Second Quadrant (-,+)",
  "चतुर्थ": "चतुर्थ चतुर्थांश / Fourth Quadrant (+,-)",
  "अपरिमित": "अपरिमित रूप से अनेक / Infinitely Many",
  "1540 सेमी³": "1540 सेमी³ / 1540 cm³",
  "1450 सेमी³": "1450 सेमी³ / 1450 cm³",
  "1500 सेमी³": "1500 सेमी³ / 1500 cm³",
  "770 सेमी³": "770 सेमी³ / 770 cm³",
  "अनिश्चित": "अनिश्चित / Indeterminate",
  "8 सेकंड": "8 सेकंड / 8 Seconds",
  "6 सेकंड": "6 सेकंड / 6 Seconds",
  "10 सेकंड": "10 सेकंड / 10 Seconds",
  "12 सेकंड": "12 सेकंड / 12 Seconds",
  "20 वर्ष": "20 वर्ष / 20 Years",
  "10 वर्ष": "10 वर्ष / 10 Years",
  "15 वर्ष": "15 वर्ष / 15 Years",
  "25 वर्ष": "25 वर्ष / 25 Years",
  "9√3 सेमी²": "9√3 सेमी² / 9√3 cm²",
  "18√3 सेमी²": "18√3 सेमी² / 18√3 cm²",
  "36 सेमी²": "36 सेमी² / 36 cm²",
  "6√3 सेमी²": "6√3 सेमी² / 6√3 cm²",
  "6 घंटे": "6 घंटे / 6 Hours",
  "8 घंटे": "8 घंटे / 8 Hours",
  "5 घंटे": "5 घंटे / 5 Hours",
  "7.5 घंटे": "7.5 घंटे / 7.5 Hours"
};

let content = fs.readFileSync('public/js/master-high-yield-bank.js', 'utf8');

let replaceCount = 0;
for (const [hindi, bilingual] of Object.entries(DICT)) {
  // Replace in options array with letter prefix (A) / B) / C) / D) )
  const regex = new RegExp(`"([A-D]\\)\\s*)${hindi.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'g');
  content = content.replace(regex, (match, prefix) => {
    replaceCount++;
    return `"${prefix}${bilingual}"`;
  });
  // Also check without prefix
  const rawRegex = new RegExp(`"${hindi.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'g');
  content = content.replace(rawRegex, () => {
    replaceCount++;
    return `"${bilingual}"`;
  });
}

console.log(`Replaced ${replaceCount} occurrences with bilingual formatting!`);
fs.writeFileSync('public/js/master-high-yield-bank.js', content, 'utf8');
console.log('Saved updated public/js/master-high-yield-bank.js');
